name: continuous-delivery
on:
  push:
    branches: [main]
jobs:
  detect-changes-in-js-files:
    name: Detect changes in JS files
    runs-on: ubuntu-latest
    outputs:
      any_change: ${{ steps.detect-changes.outputs.any_change }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Detect changes
        id: detect-changes
        run: |
          if [ "$(git diff --name-only --ignore-space-at-eol HEAD HEAD~1 | grep '.js' | wc -l)" -gt "0" ]; then
            echo "::set-output name=any_change::true"
          fi

  pack-js-and-dependencies:
    name: Packing JS and dependencies into one file
    needs: detect-changes-in-js-files
    if: needs.detect-changes-in-js-files.outputs.any_change == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CICD_GITHUB_REPOSITORY_TOKEN }}
      - name: npm install
        run: npm install
      - name: Rebuild the dist/ directory
        run: npm run prepare
      - name: Push compiled code
        working-directory: ./
        run: |
          if [ "$(git status -s | wc -l)" -gt "0" ]; then # ensure we have changes to commit
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add dist/**
            git commit -m "[skip ci] compile js code for node into one file"
            git push
          fi

  semver:
    runs-on: ubuntu-latest
    needs: pack-js-and-dependencies
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CICD_GITHUB_REPOSITORY_TOKEN }}
          ref: main

      - uses: ohpensource/generate-version-and-release-notes-gh-action@v1.0.1
        name: semver & changelog
        with:
          user-email: "github-actions@github.com"
          user-name: "github-actions"
          version-prefix: "v"
