name: continuous-integration
on:
  pull_request:
    branches: [main]

jobs:

  # make sure the next name is in the branch_protection.checks_list in your repo tfvars in the ohpensource-repo-provisioning
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ohpensource/ensure-conventional-commits-gh-action@v0.1.2
        name: Ensure conventional commits
        with:
          base-branch: $GITHUB_BASE_REF
          pr-branch: $GITHUB_HEAD_REF

  # make sure the next name is in the branch_protection.checks_list in your repo tfvars in the ohpensource-repo-provisioning
  jira-tickets-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ohpensource/ensure-commits-have-ticket-gh-action@v0.0.4
        name: Ensure Jira ticket in all commits
        with:
          base-branch: $GITHUB_BASE_REF
          pr-branch: $GITHUB_HEAD_REF

  # make sure the next name is in the branch_protection.checks_list in your repo tfvars in the ohpensource-repo-provisioning
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.3
        with:
          files: "README.md"
      - name: ensure-documentation-is-added
        if: steps.changed-files.outputs.any_modified == 'false'
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Include documentation in the README.md file!')
